apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: ioannismich/orders
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
            - name: PAYPAL_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: paypal-secret
                  key: PAYPAL_CLIENT_ID
            - name: PAYPAL_APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: paypal-secret
                  key: PAYPAL_APP_SECRET
            - name: PAYPAL_API_URL
              valueFrom:
                secretKeyRef:
                  name: paypal-secret
                  key: PAYPAL_API_URL
            - name: MONGO_URI
              value: 'mongodb://orders-mongo-srv:27017/orders'
            - name: NATS_CLUSTER_ID
              value: hat-heaven
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name # Get the name of the pod
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NODE_ENV
              value: 'development'
---
apiVersion: v1
kind: Service
metadata:
  name: orders-srv
spec:
  selector:
    app: orders
  ports:
    - name: orders
      protocol: TCP
      port: 5000
      targetPort: 5000