apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      # Init container waits for nats-srv:4222 to be reachable
      initContainers:
        - name: wait-for-nats
          image: busybox
          command: ['sh', '-c', 'until nc -z nats-srv 4222; do echo "Waiting for NATS..."; sleep 2; done']
      containers:
        - name: products
          image: ioannismich/products
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
            - name: MONGO_URI
              value: 'mongodb://products-mongo-srv:27017/products'
            - name: NATS_CLUSTER_ID
              value: hat-heaven
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name # Get the name of the pod
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NODE_ENV
              value: 'development'
---
apiVersion: v1
kind: Service
metadata:
  name: products-srv
spec:
  selector:
    app: products
  ports:
    - name: products
      protocol: TCP
      port: 5000
      targetPort: 5000