apiVersion: batch/v1
kind: Job
metadata:
  name: products-seed-job
spec:
  backoffLimit: 3
  template:
    spec:
      # Init containers wait for products-mongo-srv nats-srv to be reachable
      initContainers:
        - name: wait-for-mongo
          image: busybox
          command: ['sh', '-c', 'until nc -z products-mongo-srv 27017; do echo "Waiting for MongoDB..."; sleep 2; done']

        - name: wait-for-nats
          image: busybox
          command: ['sh', '-c', 'until nc -z nats-srv 4222; do echo "Waiting for NATS..."; sleep 2; done']
      containers:
        - name: products-seeder
          image: ioannismich/products
          command: ["npm", "run", "data:import"]
          env:
            - name: MONGO_URI
              value: "mongodb://products-mongo-srv:27017/products"
            - name: NATS_CLUSTER_ID
              value: hat-heaven
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name # Get the name of the pod
            - name: NATS_URL
              value: 'http://nats-srv:4222'
      restartPolicy: Never
